# -*- coding: utf-8 -*-
"""bishakha_Task4_Movie_Recommenders.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OBnKe2dKzunKCW74XEAnT2CnREkVwqJD
"""

import pandas as pd

# Load the necessary datasets
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')
tags = pd.read_csv('tags.csv')

movies.head(), ratings.head(), tags.head()

# Display basic info
movies.info(), ratings.info(), tags.info()

# Check for missing values
movies.isnull().sum(), ratings.isnull().sum(), tags.isnull().sum()

# Drop rows with missing values
tags.dropna(inplace=True)

# Remove duplicates
movies.drop_duplicates(inplace=True)
ratings.drop_duplicates(inplace=True)
tags.drop_duplicates(inplace=True)

movies.shape, ratings.shape, tags.shape

# Merge movies and tags data to get movie metadata (i.e., all tags for each movie)
movie_tags = tags.groupby('movieId')['tag'].apply(lambda x: ' '.join(x)).reset_index()

# Merge movie_tags with the movies dataset to get the movie title and tags
movie_metadata = pd.merge(movies, movie_tags, on='movieId', how='left')

# View the merged data
movie_metadata.head()

movie_metadata.shape

movie_metadata.isnull().sum()

movie_metadata.dropna(inplace=True)

movie_metadata.shape

# --- Popularity-based Filtering ---
# Calculate the number of ratings per movie
movie_ratings_count = ratings.groupby('movieId').size().reset_index(name='num_ratings')

# Calculate the average rating per movie
movie_avg_rating = ratings.groupby('movieId')['rating'].mean().reset_index(name='avg_rating')

# Merge popularity metrics with movies dataset
movies = pd.merge(movies, movie_ratings_count, on='movieId', how='left')
movies = pd.merge(movies, movie_avg_rating, on='movieId', how='left')

# Get top 10 most popular movies based on the number of ratings
popularity_recommendations = movies.sort_values(by='num_ratings', ascending=False).head(10)
print("Top 10 Popular Movies:")
print(popularity_recommendations[['title', 'num_ratings', 'avg_rating']])

!pip install scikit-learn

# --- Content-based Filtering ---
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD

# Apply TF-IDF Vectorizer on the 'tag' column of the metadata
tfidf = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf.fit_transform(movie_metadata['tag'])

# Apply TruncatedSVD for Latent Matrix 1 (Dimensionality reduction)
svd = TruncatedSVD(n_components=50, random_state=42)
latent_matrix_1 = svd.fit_transform(tfidf_matrix)

# --- Collaborative Filtering ---
# Create a user-movie matrix using a pivot table on ratings
user_movie_matrix = ratings.pivot_table(index='userId', columns='movieId', values='rating')

# Replace NaN values with 0 (indicating no rating)
user_movie_matrix = user_movie_matrix.fillna(0)

# Latent Matrix 2 (Collaborative Filtering via SVD)
svd_collab = TruncatedSVD(n_components=50, random_state=42)
latent_matrix_2 = svd_collab.fit_transform(user_movie_matrix)

import numpy as np
# --- Hybrid Filtering ---
# Step 1: Normalize both latent matrices (avoid division by zero)
latent_matrix_1_norm = latent_matrix_1 / (np.linalg.norm(latent_matrix_1, axis=1, keepdims=True) + 1e-10)
latent_matrix_2_norm = latent_matrix_2 / (np.linalg.norm(latent_matrix_2, axis=1, keepdims=True) + 1e-10)

# Step 2: Get the movieId order used in both matrices
movies_in_latent_1 = movie_metadata['movieId'].reset_index(drop=True)
movies_in_latent_2 = user_movie_matrix.columns

# Step 3: Get common movies
common_movies = np.intersect1d(movies_in_latent_1, movies_in_latent_2)

# Step 4: Create movie ID to index mappings
movie_to_idx_1 = {movie_id: idx for idx, movie_id in enumerate(movies_in_latent_1)}
movie_to_idx_2 = {mid: user_movie_matrix.columns.get_loc(mid) for mid in movies_in_latent_2}

# Step 5: Get the indices of common movies in both latent matrices
idx_latent_1 = [movie_to_idx_1[mid] for mid in common_movies if mid in movie_to_idx_1]
idx_latent_2 = [movie_to_idx_2[mid] for mid in common_movies if mid in movie_to_idx_2 and movie_to_idx_2[mid] < latent_matrix_2.shape[0]]

# Step 6: Ensure both lists have the same number of movies
min_length = min(len(idx_latent_1), len(idx_latent_2))

idx_latent_1, idx_latent_2 = idx_latent_1[:min_length], idx_latent_2[:min_length]

# Step 7: Slice both latent matrices using matching indices
latent_matrix_1_common = latent_matrix_1[idx_latent_1, :]
latent_matrix_2_common = latent_matrix_2[idx_latent_2, :]

# Debug: Check shapes
print(f"latent_matrix_1_common shape: {latent_matrix_1_common.shape}")
print(f"latent_matrix_2_common shape: {latent_matrix_2_common.shape}")

# Ensure matrices have the same shape before averaging
assert latent_matrix_1_common.shape == latent_matrix_2_common.shape, "Shape mismatch!"

# Step 8: Average the two matrices to get a hybrid representation
hybrid_matrix = (latent_matrix_1_common + latent_matrix_2_common) / 2

# Step 9: Compute similarity between movies using dot product
similarity_matrix = np.dot(hybrid_matrix, hybrid_matrix.T)

# Step 10: Build the recommender function
def get_hybrid_recommendations(movie_id, top_n=10):
    try:
        # Get the index of the movie in the hybrid matrix
        idx = movies_in_latent_1[movies_in_latent_1 == movie_id].index[0]
        sim_scores = list(enumerate(similarity_matrix[idx]))
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)[1:top_n+1]
        movie_indices = [i[0] for i in sim_scores]
        return movie_metadata['title'].iloc[movie_indices]
    except IndexError:
        return f"Movie ID {movie_id} not found in hybrid model."

# Example: Get recommendations for movieId = 1
get_hybrid_recommendations(1)

get_hybrid_recommendations(100)